# Generated by Django 4.0.4 on 2022-05-29 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigolibro', models.CharField(max_length=20)),
                ('localizacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadev', models.CharField(max_length=20)),
                ('fechapres', models.CharField(max_length=20)),
                ('ejemplaresid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.ejemplares')),
                ('usuarioid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='ejemplares',
            name='usuarioid',
            field=models.ManyToManyField(through='usuario.Prestar', to='usuario.usuario'),
        ),
    ]
